# Generated by Django 4.1.7 on 2023-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entrynum', models.CharField(blank=True, max_length=8, null=True)),
                ('smiles', models.CharField(blank=True, max_length=128, null=True)),
                ('pka_type', models.CharField(blank=True, max_length=512, null=True)),
                ('pka_value', models.CharField(blank=True, max_length=16, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('method', models.CharField(blank=True, max_length=8, null=True)),
                ('ref', models.CharField(blank=True, max_length=8, null=True)),
                ('ref_remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('entry_remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('original_iupac_name', models.CharField(blank=True, max_length=128, null=True)),
                ('original_iupac_nickname', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=16, null=True)),
                ('pressure', models.CharField(blank=True, max_length=16, null=True)),
                ('acidity_level', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': True,
            },
        ),
    ]
