# Generated by Django 4.1.7 on 2023-03-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_remove_references_updated'),
        ('methods', '0001_initial'),
        ('substances', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='method_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='methods.methods'),
        ),
        migrations.AddField(
            model_name='data',
            name='reference_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.references'),
        ),
        migrations.AddField(
            model_name='data',
            name='substance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='substances.substances'),
        ),
    ]
