# Generated by Django 4.1.7 on 2023-03-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_data_method_id_alter_data_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='method_id',
        ),
    ]
