# Generated by Django 4.1.7 on 2023-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substances',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('formula', models.CharField(blank=True, max_length=256, null=True)),
                ('molweight', models.FloatField(blank=True, null=True)),
                ('inchikey', models.CharField(blank=True, max_length=27, null=True)),
                ('smiles', models.CharField(blank=True, max_length=128, null=True)),
                ('iupacname', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'substances',
                'managed': True,
            },
        ),
    ]
