# Generated by Django 4.1.7 on 2023-03-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0001_initial'),
        ('data', '0003_alter_data_method_id_alter_data_reference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMethods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_id', models.ForeignKey(blank=True, db_column='data_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.data')),
                ('method_id', models.ForeignKey(blank=True, db_column='method_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='methods.methods')),
            ],
            options={
                'db_table': 'data_methods',
                'managed': True,
                'unique_together': {('data_id', 'method_id')},
            },
        ),
    ]
