# Generated by Django 4.1.7 on 2023-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('perrin', models.CharField(blank=True, max_length=256, null=True)),
                ('perrinsupp', models.CharField(blank=True, max_length=256, null=True)),
                ('serjeant', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'methods',
                'managed': True,
            },
        ),
    ]
