# Generated by Django 4.1.7 on 2023-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('citation', models.TextField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('abbrev', models.CharField(blank=True, max_length=128, null=True)),
                ('authors', models.CharField(blank=True, max_length=2048, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=6, null=True)),
                ('issue', models.CharField(blank=True, max_length=16, null=True)),
                ('startpage', models.CharField(blank=True, max_length=6, null=True)),
                ('endpage', models.CharField(blank=True, max_length=6, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('doi', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('caref', models.CharField(blank=True, max_length=16, null=True)),
                ('other', models.CharField(blank=True, max_length=512, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'references',
                'managed': True,
            },
        ),
    ]
