# Generated by Django 4.1.7 on 2023-03-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_references_code_alter_references_citation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='updated',
        ),
    ]
